### ISSUE TITLE
App name/namespace not honoured

### ISSUE THREAD

**Issue by ZeroGodForce** [GrafiteInc/Laracogs#183]
I was looking to use this as a good base for building an API, but I seem to be going round in circles.

I don't know if it's just me but having installed the starter kit, it seems like there's a long list of files that do not take on the project namespace.  Prior to configuring and installing the starter I ran `php artisan app:name` to change the namespace of my project, however, after completing all the pre-config and then running `php artisan laracogs:starter` it threw up exceptions based on my email activation choices (a bug in the UserService I believe), and then it couldn't find classes where (understandably) the namespaces were not correct.

I ran `php artisan app:name` again to see if it would have any effect but that doesn't appear to have done so, I then ran find and replace a couple of times to change what came up, but still more exceptions about classes it can't find.

Has anyone else experienced this?

**Comment by CaddyDz** [comment]
Yes, same here but find and replace solved it for me

**Comment by ZeroGodForce** [comment]
After one more try I managed to find them all and get it working, though I've now run into other problems - the origin of which I'm not sure is on the laracogs side or the JWT side but I'll open another issue for that
